services:
  mysql-course-db:
    image: mysql:latest
    container_name: mysql-course-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
  mysql-course-pma:
      container_name: mysql-course-pma
      image: phpmyadmin
      restart: unless-stopped
      ports:
            - "8090:80"
      environment:
            PMA_HOST: mysql-course-db
            MYSQL_ROOT_PASSWORD: password
      depends_on:
            - mysql-course-db
  mysql-course-faker:
      container_name: mysql-course-faker
      build: .
      volumes: 
            - ./app:/var/www/html
            - ./logs:/var/log/apache2/
      ports:
            - 8080:80
      depends_on:
            - mysql-course-db